/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.github.lgooddatepicker.components.DatePicker;
import controlador.ConsultasCliente;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionAdapter;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.UIManager;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import modelo.Usuario;

/**
 *
 * @author mescr
 */
public class VentanaCliente extends javax.swing.JFrame {

    /**
     * Creates new form VentanaCliente
     */
    private int posicionActual, id;
    private int posicionFinal;
    private Timer animacion;
    private JPanel panelSustituto;
    private ConsultasCliente consultas;
    private Usuario usu;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public VentanaCliente() {
        initComponents();
        jMenu1.setIcon(new ImageIcon("./src/images/home.png"));
        jMenu2.setIcon(new ImageIcon("./src/images/cita.png"));
//        mostrarPanelSustituto();
        vaciarPanelOpciones();
        panelOpciones.setVisible(true);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    public void setValor(int valor) {
        this.id = valor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        panelBienvenida = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        calendarPanel1 = new com.github.lgooddatepicker.components.CalendarPanel();
        panelOpciones = new javax.swing.JPanel();
        menuConsultas = new javax.swing.JLabel();
        cerrarSesion = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBienvenida.setBackground(new java.awt.Color(51, 102, 255));
        panelBienvenida.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("                           ");
        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setOpaque(true);
        panelBienvenida.add(jLabel2, java.awt.BorderLayout.EAST);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setName(""); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIENVENID@");
        jLabel1.setBackground(new java.awt.Color(20, 140, 32));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel1.setName(""); // NOI18N
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1013, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1013, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 103, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
        );

        panelBienvenida.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Hoy es:");
        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Rockwell Nova", 0, 18)); // NOI18N
        jLabel5.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.WEST);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel3.setText("                                                                                                                                                        ");
        jPanel4.add(jLabel3);

        jLabel4.setText("                                                                                                                                                        ");
        jPanel4.add(jLabel4);

        calendarPanel1.setSelectedDate(LocalDate.now());
        calendarPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.add(calendarPanel1);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        panelBienvenida.add(jPanel1, java.awt.BorderLayout.CENTER);

        panelOpciones.setBackground(new java.awt.Color(255, 255, 255));
        panelOpciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelOpcionesMouseClicked(evt);
            }
        });

        menuConsultas.setText("-> Consultar");
        menuConsultas.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        menuConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuConsultasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuConsultasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuConsultasMouseExited(evt);
            }
        });

        cerrarSesion.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        cerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarSesionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelOpcionesLayout = new javax.swing.GroupLayout(panelOpciones);
        panelOpciones.setLayout(panelOpcionesLayout);
        panelOpcionesLayout.setHorizontalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpcionesLayout.createSequentialGroup()
                        .addComponent(cerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        panelOpcionesLayout.setVerticalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(menuConsultas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cerrarSesion)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        panelBienvenida.add(panelOpciones, java.awt.BorderLayout.WEST);
        panelOpciones.getAccessibleContext().setAccessibleName("");

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setToolTipText("");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1013, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );

        panelBienvenida.add(jPanel5, java.awt.BorderLayout.SOUTH);

        getContentPane().add(panelBienvenida, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(71, 40, 184));
        jMenuBar1.setName(""); // NOI18N
        jMenuBar1.setOpaque(false);
        jMenuBar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jMenuBar1MouseReleased(evt);
            }
        });

        jMenu1.setName(""); // NOI18N
        jMenu1.setToolTipText("Home");
        jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
                jMenu1MenuDeselected(evt);
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
            }
        });
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMenu1MouseExited(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setToolTipText("Citas");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenu2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMenu2MouseExited(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseEntered
        jMenu1.setSelected(false);
    }//GEN-LAST:event_jMenu1MouseEntered

    private void jMenuBar1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MouseReleased

    }//GEN-LAST:event_jMenuBar1MouseReleased

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        jMenu1.setSelected(false);
        if (evt.getClickCount() <= 1) {
            menuConsultas.setText("-> Consultar mis datos");
            cerrarSesion.setText("-> Cerrar sesión");
        }
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        jMenu2.setSelected(false);
        if (menuConsultas.getText().contains("Consultar citas") && !cerrarSesion.getText().contains("-> Cerrar sesión")) {
        } else {
            menuConsultas.setText("-> Consultar citas");
            cerrarSesion.setText(" ");
        }
        mostrarPanelOculto();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu1MenuDeselected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu1MenuDeselected

    }//GEN-LAST:event_jMenu1MenuDeselected

    private void jMenu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseExited
        jMenu1.setSelected(false);
    }//GEN-LAST:event_jMenu1MouseExited

    private void jMenu2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseEntered
        jMenu2.setSelected(false);
    }//GEN-LAST:event_jMenu2MouseEntered

    private void jMenu2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseExited
        jMenu2.setSelected(false);
    }//GEN-LAST:event_jMenu2MouseExited

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void panelOpcionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOpcionesMouseClicked

    }//GEN-LAST:event_panelOpcionesMouseClicked

    private void menuConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuConsultasMouseClicked
        // TODO add your handling code here:
        if (menuConsultas.getText().contains("Consultar citas")) {
            JOptionPane.showMessageDialog(null, "Abriendo el menu de consultas");
            dispose();
            GestionCitasCliente gc = new GestionCitasCliente();
            gc.setValor(id);
            gc.comprobarTabla();
            gc.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Mostrando datos del perfil");
            mostrarTablaDatos();
        }
    }//GEN-LAST:event_menuConsultasMouseClicked

    private void mostrarTablaDatos() throws HeadlessException {
        consultas = new ConsultasCliente();
        // Nombres de las columnas
        String[] columnNames = {"Nombre", "Apellidos", "Telefono", "Email", "Cuenta", "Contrasenia"};
        DefaultTableModel modelo = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        consultas.realizarConexion();
        String mostrarDatos = "SELECT id,nombre,apellidos,telefono,email,cuenta,contrasenia FROM usuario WHERE id=?";
        try {
            PreparedStatement psDatos = consultas.getCon().prepareStatement(mostrarDatos);
            if (id != 0) {
                psDatos.setInt(1, id);
                ResultSet resul = psDatos.executeQuery();
                while (resul.next()) {
                    int idCliente = resul.getInt("id");
                    String nombre = resul.getString("nombre");
                    String apellidos = resul.getString("apellidos");
                    String telefono = String.valueOf(resul.getInt("telefono"));
                    String email = resul.getString("email");
                    String cuenta = resul.getString("cuenta");
                    String contrasenia = resul.getString("contrasenia");
                    usu = new Usuario(id, nombre, apellidos, Integer.parseInt(telefono), email, cuenta, contrasenia);
                    String fila[] = {nombre, apellidos, telefono, email, cuenta, contrasenia};
                    modelo.addRow(fila);
                }
                // Crear el JTable
                JTable table = new JTable(modelo);
                // Agregar el MouseMotionListener para mostrar el tooltip con el valor completo
                // Agregar el MouseMotionListener para mostrar el registro completo en el ToolTipText
                table.addMouseMotionListener(new MouseMotionAdapter() {
                    @Override
                    public void mouseMoved(MouseEvent e) {
                        int row = table.rowAtPoint(e.getPoint());
                        if (row > -1) {
                            StringBuilder tooltip = new StringBuilder();
                            for (int col = 0; col < table.getColumnCount(); col++) {
                                Object value = table.getValueAt(row, col);
                                tooltip.append(table.getColumnName(col)).append(": ").append(value).append("<br>");
                            }
                            table.setToolTipText("<html>" + tooltip.toString() + "</html>");
                        } else {
                            table.setToolTipText(null);
                        }
                    }
                });
                // Crear el menú emergente
                JPopupMenu popupMenu = new JPopupMenu();
                JMenuItem menuItem = new JMenuItem("Modificar");
                menuItem.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        consultas.modificarUsuario(id);
                        JOptionPane.getRootFrame().dispose();
                    }
                });
                popupMenu.add(menuItem);
                // Asociar el menú emergente a la tabla
                table.setComponentPopupMenu(popupMenu);
                // Ajustar el ancho de las columnas al contenido
                table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
                table.setRowHeight(table.getRowHeight() + 5);
                // Ajustar el tamaño de las celdas al contenido
                DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
                renderer.setHorizontalAlignment(DefaultTableCellRenderer.LEFT);
                table.setDefaultRenderer(String.class, renderer);
                // Crear el JScrollPane para agregar el JTable
                JScrollPane scrollPane = new JScrollPane(table);
                // Mostrar el JTable en el JOptionPane
                JOptionPane.showMessageDialog(null, scrollPane, "Datos del usuario", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "No hay datos que mostrar");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error mostrando datos");
        }
    }

    private void menuConsultasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuConsultasMouseEntered
        menuConsultas.setForeground(Color.GRAY);
        menuConsultas.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuConsultasMouseEntered

    private void menuConsultasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuConsultasMouseExited
        menuConsultas.setForeground(Color.BLACK);
    }//GEN-LAST:event_menuConsultasMouseExited

    private void cerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionMouseClicked
        // TODO add your handling code here:
        if (cerrarSesion.getText().contains("Cerrar sesión")) {
            int decision = JOptionPane.showConfirmDialog(null, "¿Seguro que desea cerrar sesión?");
            if (decision == JOptionPane.YES_OPTION) {
                dispose();
                VentanaLog vl = new VentanaLog();
                vl.setVisible(true);
            }
        }
    }//GEN-LAST:event_cerrarSesionMouseClicked

    private void cerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionMouseEntered
        // TODO add your handling code here:
        cerrarSesion.setForeground(Color.GRAY);
        cerrarSesion.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_cerrarSesionMouseEntered

    private void cerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarSesionMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.CalendarPanel calendarPanel1;
    private javax.swing.JLabel cerrarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel menuConsultas;
    private javax.swing.JPanel panelBienvenida;
    private javax.swing.JPanel panelOpciones;
    // End of variables declaration//GEN-END:variables

    /* private void mostrarPanelSustituto() {
        panelSustituto = new JPanel();
        panelSustituto.setSize(new Dimension(189, 278));
        panelSustituto.setVisible(true);
        panelBienvenida.add(panelSustituto, BorderLayout.WEST);
    }*/
    private void mostrarPanelOculto() {
//        panelSustituto.setVisible(false);
        panelOpciones.setVisible(true);
    }

    private void vaciarPanelOpciones() {
        menuConsultas.setText("                    ");
    }
}
